<?php
/**
 * Application level Controller
 *
 * This file is application-wide controller file. You can put all
 * application-wide controller-related methods here.
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       app.Controller
 * @since         CakePHP(tm) v 0.2.9
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

App::uses('Controller', 'Controller');

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @package		app.Controller
 * @link		http://book.cakephp.org/2.0/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{

    public $cacheAction = false;
    public $components = array(
        'Flash',
        'Auth' => array(
            'loginRedirect' => array('controller' => 'panel', 'action' => 'index'),
            'logoutRedirect' => '/',
            'loginAction' => array('controller' => 'homes', 'action' => 'login'),
            'authError' => 'You must be logged in to view this page.',
            'loginError' => 'Invalid Username or Password entered, please try again.',
            'authenticate' => array(
                'Form' => array(
                    'passwordHasher' => 'Blowfish'
                )
            ),
            'userModel' => 'User'

        ));

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub

        $this->loadModel('User');

        $userBalance = $this->User->find('first', array(
            'fields' => array('balance'),
            'conditions' => array(
                'id' => $this->Auth->user('id')
            )
        ));
        $userBalance = empty($userBalance) ? 0 : $userBalance['User']['balance'];

        $menuItems = $this->_getMenuItems($this->Auth->user('role'));

        $this->set('leftItems', $menuItems);
        $this->set('userBalance', $userBalance);
        $this->set('Auth', $this->Auth);
    }

    private function _getMenuItems($role)
    {
        $leftItems = array();

        if (isset($role)) {
            switch ($role) {
                case '1':
                    $leftItems = array(
                        array(
                            'label' => "Dashboard",
                            'url' => "panel/index",
                            'icon' => "fa-dashboard"
                        ),
                        array(
                            'label' => "Deals",
                            'url' => "deals/index",
                            'icon' => "fa-handshake-o"
                        ),
                        array(
                            'label' => 'Finances',
                            'url' => "finances/index",
                            'icon' => "fa-money",
                            'subItems' => array(
                                array(
                                    'label' => 'Deposit',
                                    'url' => "finances/pay",
                                    'icon' => "fa-dollar"
                                ),
                                array(
                                    'label' => 'Cash Out',
                                    'url' => "finances/cash_out",
                                    'icon' => "fa-dollar"
                                ),
                                array(
                                    'label' => 'Transactions History',
                                    'url' => "finances/history",
                                    'icon' => "fa-bar-chart-o"
                                )
                            )
                        )
                    );
                    break;
                case '2':
                    $leftItems = array(
                        array(
                            'label' => "Dashboard",
                            'url' => "panel/index",
                            'icon' => "fa-dashboard"
                        ),
                        array(
                            'label' => "Deals",
                            'url' => "arbiter/deals",
                            'icon' => "fa-handshake-o"
                        ),
                    );
                    break;
                case '3':
                    $leftItems = array(
                        array(
                            'label' => "Dashboard",
                            'url' => "panel/index",
                            'icon' => "fa-dashboard"
                        ),
                        array(
                            'label' => "Deals",
                            'url' => "admin/deals",
                            'icon' => "fa-handshake-o"
                        ),
                        array(
                            'label' => "Arbiters",
                            'url'   => "admin/arbiters",
                            'icon'  => "fa-eye"
                        ),
                    );
                    break;
            }
        }

        return $leftItems;
    }
}
